key:
  security_adress: http://localhost:8081/api/auth/

logging:
  level:
    root: info

spring:
  application.name: api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        add-to-simple-url-handler-mapping: true
      routes:
        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            Path=/eureka/web
          filters:
            SetPath=/

        - id: eureka-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

        - id: eureka-client
          uri: lb://eureka-client
          predicates:
            - Path=/

        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/api/auth/**

        - id: panda-service
          uri: lb://panda-service
          predicates:
            - Path=/api/panda/**
          filters:
            - AuthenticationFilter

        - id: telbot-service
          uri: lb://telbot-service
          predicates:
            - Path=/api/i113/telegrambot/**

        - id: sales-area-service
          uri: lb://sales-area-service
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter

        - id: bornlist-service
          uri: lb://bornlist-service
          predicates:
            - Path=/api/i113/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




