server:
  port: 8080

spring:
  profiles:
    active: dev
#    active: prod

logging:
  level:
    root: info

management:
  endpoint:
    info:
      enable: true
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,loggers
  metrics:
    enable:
      jvm: true
